---
- name: Remove existing Kernel
  zypper:
    name: "{{ item }}"
    state: absent
  with_items:
    - kernel-default-debuginfo
    - kernel-default-debugsource
    - kernel-default-devel

- name: Install specific Kernel
  zypper:
    name: "{{ item }}"
    state: absent
  with_items:
    - kernel-default-debuginfo="{{ kernel version }}"
    - kernel-default-debugsource="{{ kernel version }}"
    - kernel-default-devel="{{ kernel version }}"
