#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
- name: Pre-create /etc/ceph
  file:
    path: "{{ ceph_dir }}"
    state: directory

- name: Set fact for SubjectAltNames for the host certificate.
  set_fact:
    host_cert_sans: >
      {{ groups['mons'] | map('extract', hostvars, 'ansible_fqdn') | list }} +
      {{ host_certificate_extra_altnames }} + {{ groups['mons'] | map('extract', hostvars, 'inventory_hostname') | list }} +
      {{ host_certificate_aliases }}

- name: Check if Manager host key must be regenerated
  stat:
    path: "/etc/ceph/{{ host_certificate_key }}"
  register: generate_host_key
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Create new Manager host key
  command: >-
         openssl req -new
         -keyout {{host_certificate_key}} -nodes
               -config {{cray_ca_openssl_cnf}}
               -out {{host_certificate_req}}
               -subj /C=XX/ST=XX/L=XX/O=XX/OU=XX/CN=sms/
  args:
    chdir: "{{ceph_dir}}"
  when: generate_host_key.stat.exists == False
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Set file permissions on Manager host key
  file:
    path: "{{host_certificate_key}}"
    mode: 0600
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Create host.san
  template:
    src: host.san
    dest: "{{host_certificate_san}}"
    mode: 0644
  when: generate_host_key.stat.exists == False
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Remove the old cert from the index, duplicate is ok.
  lineinfile:
    path: "{{ cray_ca_db_index }}"
    regexp: "/C=XX/ST=XX/O=XX/OU=XX/CN=sms"
    state: absent
  when: generate_host_key.stat.exists == False
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Create new Manager host crt
  command: >-
         openssl ca -batch -config {{cray_ca_openssl_cnf}}
           -out {{host_certificate_crt}}
           -extensions alt_name_extensions
           -extfile {{host_certificate_san}}
           -infiles {{host_certificate_req}}
  args:
    chdir: "{{ceph_dir}}"
  when: generate_host_key.stat.exists == False
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Set file permissions on Manager host crt
  file:
    path: "{{host_certificate_crt}}"
    mode: 0600
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Create pem file for rgw
  shell: "cat /etc/ceph/host.key /etc/ceph/host.crt >  /etc/ceph/rgw.pem"
  args:
    executable: /bin/bash
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True

- name: Copy files to mons nodes
  synchronize:
    src: /etc/ceph/rgw.pem
    dest: /etc/ceph/rgw.pem
  delegate_to: "{{ groups.mons|first }}"
  when: inventory_hostname != groups.mons|first

- name: Clean up
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{host_certificate_san}}"
    - "{{host_certificate_req}}"
    - "{{host_certificate_crt}}"
    - "{{host_certificate_key}}"
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True
