#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
nameOverride: "gce-ingress"
fullnameOverride: "gce-ingress"

# gce-ingress needs credentials to log into GCE.  Create a secret with the key
# of key.json with the contents of a GCE service account that has permissions to create
# and modify load balancers.  The key should be in the JSON format.
# Example:
# Your secret should look like:
# apiVersion: v1
# kind: Secret
# metadata:
#   name: gce-key
# type: Opaque
# data:
#   key.json: < base64 encoded JSON service account key>
secretName: "${GCE_INGRESS_SECRET_NAME}"
configMapName: "${GCE_INGRESS_CONFIGMAP_NAME}"

controller:
  replicas: 1
  image:
    repository: k8s.gcr.io/ingress-gce-glbc-amd64
    tag: v1.6.1
    pullPolicy: IfNotPresent

backend:
  replicas: 1
  image:
    repository: k8s.gcr.io/defaultbackend-amd64
    tag: "1.5"
    pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
