---
#- name: Install Base Packages
#  zypper:
#    oldpackage: yes
#    name: "{{ base_packages }}"
#    state: present
#  tags:
#    - common
#
#- name: Install Metal Packages
#  zypper:
#    name: "{{ metal_packages }}"
#    state: present
#  tags:
#    - metal
#
#- name: Install CMS Packages
#  zypper:
#    name: "{{ cms_packages }}"
#    state: present
#  tags:
#    - common

- name: Symlink python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  tags:
    - common

- name: Ensuring /srv/cray/utilities locations are available for use system-wide
  file:
    src: /srv/cray/utilities/common/craysys/craysys
    dest: /bin/craysys
    state: link
  tags:
    - common

- name: Export cray path
  lineinfile:
    path: /etc/profile.d/cray.sh
    regexp: '^export PYTHONPATH='
    line: 'export PYTHONPATH="/srv/cray/utilities/common"'
  tags:
    - common

- name: Configuring podman so it will run with fuse-overlayfs
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^mount_program ='
    line: 'mount_program = "/usr/bin/fuse-overlayfs"'
  tags:
    - common

- name: Enable multi-user target
  systemd:
    name: multi-user.target
    enabled: yes
    masked: no
  tags:
    - common

- name: "Get current systemd default"
  command: "systemctl get-default"
  changed_when: false
  register: systemdefault
  tags:
    - common

- name: "Set default to multi-user target"
  command: "systemctl set-default multi-user.target"
  when: "'multi-user' not in systemdefault.stdout"
  tags:
    - common

- name: Enabling services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    with_items:
      - ca-certificates.service
      - issue-generator.service
      - kdump-early.service
      - kdump.service
      - purge-kernels.service
      - rasdaemon.service
      - rc-local.service
      - rollback.service
      - sshd.service
      - wicked.service
      - wickedd-auto4.service
      - wickedd-dhcp4.service
      - wickedd-dhcp6.service
      - wickedd-nanny.service
      - getty@tty1.service
      - serial-getty@ttyS0.service
      - lldpad.service
      - chronyd.service
      - spire-agent.service
  tags:
    - common

- name: Disable postfix service
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
    with_items:
      - postfix.service
  tags:
    - common

- name: Make virtualenv available to all contexts and teams.
  pip:
    name: virtualenv
  tags:
    - common

- name: "Copy sysstat service into place"
  copy:
    remote_src: yes
    src: /srv/cray/resources/metal/sysstat.cron
    dest: /etc/sysstat/sysstat.cron
  tags:
    - metal
  register: copy_sysstat_service

- name: Disk stuff
  command: "/usr/lib64/sa/sa1 -S DISK 1 1"
  when: copy_sysstat_service.changed
  tags:
    - metal

- name: Enable sysstat service
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    with_items:
      - sysstat.service
  tags:
    - metal

- name: "Copy mdadm.conf into place"
  copy:
    remote_src: yes
    src: /srv/cray/resources/metal/mdadm.conf
    dest: /etc/mdadm.conf
  tags:
    - metal

# Agentless Management Service only works on servers with iLO4/5.
# Disable by default, enable during runtime.
- name: Disabling Agentless Management Daemon
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
    with_items:
      - ahslog
      - amsd
      - cpqFca
      - cpqIde
      - cpqScsi
      - smad
    tags:
      - metal

- name: Allow domains
  lineinfile:
    path: /etc/sysconfig/network/dhcp
    regexp: '^DHCLIENT_FQDN_ENABLED='
    line: 'DHCLIENT_FQDN_ENABLED="enabled"'
  tags:
    - metal

- name: Notify update on hostname change
  lineinfile:
    path: /etc/sysconfig/network/dhcp
    regexp: '^DHCLIENT_FQDN_UPDATE='
    line: 'DHCLIENT_FQDN_UPDATE="both"'
  tags:
    - metal

- name: Do not let DHCP set hostname, this is set by cloud-init
  lineinfile:
    path: /etc/sysconfig/network/dhcp
    regexp: '^DHCLIENT_SET_HOSTNAME='
    line: 'DHCLIENT_SET_HOSTNAME="no"'
  tags:
    - metal
