#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
cray_ca_root_dir: "/var/opt/cray/certificate_authority"
cray_ca_db_certs_dir: "{{cray_ca_root_dir}}/ca.db.certs"
cray_ca_hosts_dir: "{{cray_ca_root_dir}}/hosts"
cray_ca_clients_dir: "{{cray_ca_root_dir}}/clients"
cray_ca_db_serial: "{{cray_ca_root_dir}}/ca.db.serial"
cray_ca_db_index: "{{cray_ca_root_dir}}/ca.db.index"
cray_ca_db_rand: "{{cray_ca_root_dir}}/ca.db.rand"
cray_ca_openssl_cnf: "{{cray_ca_root_dir}}/openssl.cnf"
cray_ca_root_key: "{{cray_ca_root_dir}}/certificate_authority.key"
cray_ca_root_crt: "{{cray_ca_root_dir}}/certificate_authority.crt"
