name: Image Merge Strategy
on:
  pull_request:
    branches:
      - develop
      - main
      - lts/csm-1.0
  issue_comment:
    types: [created]
jobs:
  fast_forward_job:
    name: Fast Forward
    runs-on: ubuntu-latest
    steps:
      - name: Fast Forward PR
        id: ff
        uses: endre-spotlab/fast-forward-js-action@2.1
        if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          production_branch: main
          staging_branch: develop
       
      - if: ${{ steps.ff.outcome == 'skipped' }}
        run: |
          echo >&2 "Can not run fast-forward, yet; PR gates not met, or a rebase is required."
          exit 1
